---
### USER ROLES DEFINITION
### Create a new role by adding another hash with a unique name of the role as well as a list of rights. Unassignable states that the role cannot be assigned to users.
### Available rights are: 'user', 'biblreview', 'delete_published', 'administrate'
roles:
  -
    name: ADMIN
    rights:
      - user
      - biblreview
      - delete_published
      - administrate
  -
    name: USER
    rights:
      - user
  -
    name: API_KEY
    rights:
      - user
      - biblreview
      - delete_published
      - administrate
    type: api
    unassignable: true
  -
    name: API_USER
    rights:
      - user
    type: api
    unassignable: true
