---
api_key_users:
  -
    username: "test_key_user"
    first_name: "Test"
    last_name: "Key User"
    role: "API_KEY"
    api_key: "an-api-key"

external_auth_url: 'https://login-server.example.com/auth'
journal_index_url: 'http://gup_solr:8983/solr/gup-journals/'
publication_index_url:  'http://gup_solr:8983/solr/gup-publications/'
person_index_url:  'http://gup_solr:8983/solr/gup-people/'
gu_research_index_url:  'http://gup_solr:8983/solr/gup-guresearch/'

file_upload_root_dir: '/data/gup'
sitemaps_dir: '/apps/gup/sitemaps'

datasource_api_keys:
  scopus: 'SCOPUS-ID'

mail_settings:
  delivery_options:
    address: ''
    port: 25
  from_email: ''
  to_email: ''

public_base_url: 'http://localhost:6311/'
publication_path: 'publication/'
file_path: 'file/'

university:
  name_sv: 'Göteborgs universitet'
  name_en: 'Gothenburg University'
repository_name: 'Gothenburg University Publications (GUP)'

oai_settings:
  max_no_of_records: 100
  repository_name: 'GUP'
  repository_url: 'http://localhost:6310/oai'
  record_prefix: 'oai:gup.devel'
  admin_email: ''
  record_content_source: 'gu'

override_file: '/var/tmp/gup_auth_override.enable'
