version: '3'
services:
  gup_backend:
    image: "docker.ub.gu.se/gup-backend:dev-2019-05-001"
    depends_on:
     - gup_database
     - gup_solr
    ports:
     - "6310:3000"
    volumes:
     - ${GUP_REPO:-.}/backend:/apps/application/
     - ${GUP_REPO:-.}/files:/files/
  gup_frontend:
    image: "docker.ub.gu.se/gup-frontend:dev-2019-05-001"
    depends_on:
     - gup_backend
    ports:
     - "6311:4200"
     - "35730:35730"
    volumes:
     - ${GUP_REPO:-.}/frontend:/apps/application/
     - ${GUP_REPO:-.}/files:/files/
    user: $UID
  gup_database:
    image: "docker.ub.gu.se/gup-database:dev-2019-05-001"
    ports:
        - "6312:5432"
    volumes:
    - ${GUP_REPO:-.}/files:/files/
  gup_solr:
    image: "docker.ub.gu.se/gup-solr:dev-2019-05-001"
    ports:
        - "6313:8983"
    volumes:
    - ${GUP_REPO:-.}/files:/files/
    depends_on:
     - gup_database

