#!/bin/bash

source validate_stage.sh

levant render \
  -var-file=vars/gup.yml \
  -var-file=vars/secrets.yml \
  -var-file=vars/publication_create_sitemaps.yml \
  -var-file=vars/$1.yml \
  templates/gup-bash-template.nomad > jobs/gup-publication-create-sitemaps.nomad  \
  && nomad job run jobs/gup-publication-create-sitemaps.nomad
