#!/bin/bash

source validate_stage.sh
source validate_periodic.sh

levant render \
  -var "periodic=$PERIODIC" \
  -var-file=vars/gup.yml \
  -var-file=vars/secrets.yml \
  -var-file=vars/solr_full_index.yml \
  -var-file=vars/$1.yml \
  templates/gup-bash-template.nomad > jobs/${PERIODIC_PREFIX}gup-solr-full-index.nomad \
  && nomad job run jobs/${PERIODIC_PREFIX}gup-solr-full-index.nomad
