version: '3.7'
services:
  frontend:
    ports:
      - ${GUP_FRONTEND_PORT}:8080
  backend:
    endpoint_mode: dnsrr
  db:
    deploy:
      placement:
        constraints: [node.role == manager]
networks:
  backend:
    driver: overlay
    attachable: true
