version: '3.7'
services:
  frontend:
    image: docker.ub.gu.se/gup-frontend:${GIT_REVISION}
    environment:
      - EMBER_ENVIRONMENT=${GUP_ENVIRONMENT}
      - GUP_SERVICE_PORT=${GUP_BACKEND_PORT}
    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as debugging, etc
    stdin_open: true
    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container
    tty: true
    ports:
      # TODO: Change production image to 4200 instead of 8080
      # so dont have to override here
      # server
      - ${GUP_FRONTEND_PORT}:4200
      # livereload
      - 7020:7020
      # Tests in browser
      - 7357:7357
  backend:
    image: docker.ub.gu.se/gup-backend:${GIT_REVISION}
    depends_on:
      - db
    environment:
      - RAILS_ENV=${GUP_ENVIRONMENT}
      - RACK_ENV=${GUP_ENVIRONMENT}
      - RAILS_PORT=${GUP_RAILS_PORT}
      - GUP_SECRET_KEY_BASE=${GUP_SECRET_KEY_BASE}
      - GUP_DB_HOST=${GUP_DB_HOST}
      - GUP_DB_PORT=${GUP_DB_PORT}
      - GUP_DB=${GUP_DB}
      - GUP_DB_USER=${GUP_DB_USER}
      - GUP_DB_PASSWORD=${GUP_DB_PASSWORD}
      - GUP_TEST_USER_API_KEY=${GUP_TEST_USER_API_KEY}
      - GUP_SCOPUS_API_KEY=${GUP_SCOPUS_API_KEY}
      - GUP_MAIL_SMTP_HOST=${GUP_MAIL_SMTP_HOST}
      - GUP_MAIL_FROM=${GUP_MAIL_FROM}
      - GUP_MAIL_TO=${GUP_MAIL_TO}
      - GUP_PUBLIC_BASE_URL=http://localhost:${GUP_BACKEND_PORT}
      - GUP_REPOSITORY_NAME=${GUP_REPOSITORY_NAME}
      - GUP_OAI_REPOSITORY_NAME=${GUP_OAI_REPOSITORY_NAME}
      - GUP_OAI_REPOSITORY_URL=http://localhost:${GUP_BACKEND_PORT}/oai
      - GUP_OAI_RECORD_PREFIX=${GUP_OAI_RECORD_PREFIX}
      - GUP_MQ_BASE_URL=${GUP_MQ_BASE_URL}
      - GUP_MQ_API_KEY=${GUP_MQ_API_KEY}
    networks:
      - backend
    ports:
      - ${GUP_BACKEND_PORT}:${GUP_RAILS_PORT}
  db:
    image: docker.ub.gu.se/gup-postgres:${GIT_REVISION}
    restart: always
    environment:
      - POSTGRES_DB=${GUP_DB}
      - POSTGRES_USER=${GUP_DB_USER}
      - POSTGRES_PASSWORD=${GUP_DB_PASSWORD}
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    volumes:
      - ./postgres-initdb.d:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data
    networks:
      - backend
  solr:
    image: docker.ub.gu.se/gup-solr:${GIT_REVISION}
    environment:
      - GUP_SOLR_DATA_IMPORT_DB_URL=jdbc:postgresql://db:5432/${GUP_DB}
      - GUP_SOLR_DATA_IMPORT_DB_USER=${GUP_DB_USER}
      - GUP_SOLR_DATA_IMPORT_DB_PASSWORD=${GUP_DB_PASSWORD}
    networks:
      - backend
    depends_on:
      - db
    ports:
      - ${GUP_SOLR_PORT}:8983
networks:
  backend:

volumes:
  dbdata:
