version: '3.7'
services:
  frontend:
    environment:
      - EMBER_ENVIRONMENT=${GUP_ENVIRONMENT}
    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as debugging, etc
    stdin_open: true
    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container
    tty: true
    restart: always
  backend:
    depends_on:
      - db
    environment:
      - RAILS_ENV=${GUP_ENVIRONMENT}
      - RAILS_PORT=${GUP_RAILS_PORT}
      - GUP_AUTH_OVERRIDE=${GUP_AUTH_OVERRIDE}
      - GUP_SECRET_KEY_BASE=${GUP_SECRET_KEY_BASE}
      - GUP_DB_HOST=${GUP_DB_HOST}
      - GUP_DB_PORT=${GUP_DB_PORT}
      - GUP_DB=${GUP_DB}
      - GUP_DB_USER=${GUP_DB_USER}
      - GUP_DB_PASSWORD=${GUP_DB_PASSWORD}
      - GUP_SOLR_HOST=solr
      - GUP_SOLR_PORT=8983
      - GUP_TEST_USER_API_KEY=${GUP_TEST_USER_API_KEY}
      - GUP_SCOPUS_API_KEY=${GUP_SCOPUS_API_KEY}
      - GUP_SMTP_SERVER=${GUP_SMTP_SERVER}
      - GUP_SMTP_PORT=${GUP_SMTP_PORT}
      - GUP_SMTP_AUTH=${GUP_SMTP_AUTH}
      - GUP_SMTP_USERNAME=${GUP_SMTP_USERNAME}
      - GUP_SMTP_PASSWORD=${GUP_SMTP_PASSWORD}
      - GUP_SMTP_ENABLE_STARTTLS_AUTO=${GUP_SMTP_ENABLE_STARTTLS_AUTO}
      - GUP_MAIL_FROM=${GUP_MAIL_FROM}
      - GUP_MAIL_TO=${GUP_MAIL_TO}
      - GUP_REPOSITORY_NAME=${GUP_REPOSITORY_NAME}
      - GUP_OAI_REPOSITORY_NAME=${GUP_OAI_REPOSITORY_NAME}
      - GUP_OAI_RECORD_PREFIX=${GUP_OAI_RECORD_PREFIX}
      - GUP_MQ_BASE_URL=${GUP_MQ_BASE_URL}
      - GUP_MQ_API_KEY=${GUP_MQ_API_KEY}
    networks:
      - backend
    ports:
      - ${GUP_BACKEND_PORT}:${GUP_RAILS_PORT}
    restart: always
  db:
    environment:
      - POSTGRES_DB=${GUP_DB}
      - POSTGRES_USER=${GUP_DB_USER}
      - POSTGRES_PASSWORD=${GUP_DB_PASSWORD}
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    volumes:
      - ./postgres-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - backend
    restart: always
  solr:
    image: docker.ub.gu.se/gup-solr:${GIT_REVISION}
    environment:
      - GUP_SOLR_DATA_IMPORT_DB_URL=jdbc:postgresql://db:5432/${GUP_DB}
      - GUP_SOLR_DATA_IMPORT_DB_USER=${GUP_DB_USER}
      - GUP_SOLR_DATA_IMPORT_DB_PASSWORD=${GUP_DB_PASSWORD}
    networks:
      - backend
    depends_on:
      - db
    ports:
      - ${GUP_SOLR_PORT}:8983
    restart: always
networks:
  backend:
