languages:
  -
    en: English
    sv: Engelska
    code: en
  -
    en: Swedish
    sv: Svenska
    code: sv
  -
    en: Arabic
    sv: Arabiska
    code: AR
  -
    en: Bosnian
    sv: Bosniska
    code: bs
  -
    en: Bulgarian
    sv: Bulgariska
    code: BG
  -
    en: Chinese(Mandarin)
    sv: Kinesiska (Mandarin)
    code: ZH
  -
    en: Croatian
    sv: Kroatiska
    code: HR
  -
    en: Czech
    sv: Tjeckiska
    code: CS
  -
    en: Danish
    sv: Danska
    code: DA
  -
    en: Dutch
    sv: Nederländska
    code: NL
  -
    en: Esperanto
    sv: Esperanto
    code: EO
  -
    en: Finnish
    sv: Finska
    code: FI
  -
    en: French
    sv: Franska
    code: FR
  -
    en: German
    sv: Tyska
    code: DE
  -
    en: Greek
    sv: Grekiska
    code: EL
  -
    en: Hebrew
    sv: Hebreiska
    code: HE
  -
    en: Hungarian
    sv: Ungerska
    code: HU
  -
    en: Icelandic
    sv: Isländska
    code: IS
  -
    en: Italian
    sv: Italienska
    code: IT
  -
    en: Japanese
    sv: Japanska
    code: JA
  -
    en: Korean
    sv: Koreanska
    code: KO
  -
    en: Latin
    sv: Latin
    code: LA
  -
    en: Latvian
    sv: Lettiska
    code: LV
  -
    en: Norwegian
    sv: Norska
    code: "NO"
  -
    en: Polish
    sv: Polska
    code: PL
  -
    en: Portugese
    sv: Portugisiska
    code: PT
  -
    en: Romanian
    sv: Rumänska
    code: RO
  -
    en: Russian
    sv: Ryska
    code: RU
  -
    en: Serbian
    sv: Serbiska
    code: SR
  -
    en: Slovak
    sv: Slovakiska
    code: SK
  -
    en: Slovenian
    sv: Slovenska
    code: SL
  -
    en: Spanish
    sv: Spanska
    code: ES
  -
    en: Turkish
    sv: Turkiska
    code: TR
  -
    en: Ukranian
    sv: Ukrainska
    code: UK
  -
    en: Other
    sv: Övrigt
    code: OTHER

# Put code mappings here between occuring versions in imported publications that do not correlate to 2 char standard
language_code_map:
  eng: en
  swe: se
