FROM postgres:9.3

#COPY prepare.sql prepare.sh gup-production.dmp ./
COPY gup-production.dmp .
COPY prepare.sh prepare.sql  ./

RUN echo "Europe/Stockholm" > /etc/timezone && \
    dpkg-reconfigure -f noninteractive tzdata && \
    sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    sed -i -e 's/# sv_SE.UTF-8 UTF-8/sv_SE.UTF-8 UTF-8/' /etc/locale.gen && \
    echo 'LANG="sv_SE.UTF-8"'>/etc/default/locale && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=sv_SE.UTF-8

ENV LANG sv_SE.UTF-8
ENV LANGUAGE sv_SE.UTF-8
ENV LC_ALL sv_SE.UTF-8
